name: Environment Creation Workflow
on: 
  issues:
    types: [labeled]

env:
  LOCATION: australiaeast

jobs:
  build:
    name: EnvironmentCreation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: wviriya/azure-iac/.github/actions/request-parser@master
        id: parser

      - uses: azure/login@v1
        if: steps.parser.outputs.approved
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deployment of template    
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1.0.1
        if: steps.parser.outputs.approved && steps.parser.outputs.armTemplate != 'spa-web-app'
        with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription
          scope: resourcegroup
          # Provide the target region, only required for management Group or Subscription deployments.
          region: ${{ env.LOCATION }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
          # Provide the name of a resource group, only required for resource Group deployments.
          resourceGroupName: ${{ steps.parser.outputs.resourceGroup }}
          template: ${{ github.workspace }}/templates/${{ steps.parser.outputs.armTemplate }}/azuredeploy.json  # Set this to the location of your template file
          parameters: name=${{ steps.parser.outputs.appName }} password=${{ secrets.DefaultPassword }}

      # Deployment of template    
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1.0.1
        if: steps.parser.outputs.approved && steps.parser.outputs.armTemplate == 'spa-web-app'
        with:
          # Provide the scope of the deployment. Valid values are: 'resourcegroup', 'managementgroup', 'subscription
          scope: resourcegroup
          # Provide the target region, only required for management Group or Subscription deployments.
          region: ${{ env.LOCATION }}
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
          # Provide the name of a resource group, only required for resource Group deployments.
          resourceGroupName: ${{ steps.parser.outputs.resourceGroup }}
          template: ${{ github.workspace }}/templates/${{ steps.parser.outputs.armTemplate }}/azuredeploy.json  # Set this to the location of your template file
          parameters: name=${{ steps.parser.outputs.appName }} identity=${{ secrets.MSI }}

      - uses: peter-evans/create-or-update-comment@v1.0.0
        if: steps.parser.outputs.approved
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ### 🚀All Set! 🚀
            Check your Azure Subscription for Resource Group: **${{ steps.parser.outputs.resourceGroup }}**
          reaction-type: hooray
